controllers/ConstructController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Products;
use app\models\Type;
use app\models\UploadForm;
use yii\web\UploadedFile;
use vova07\fileapi\actions\UploadAction as FileAPIUpload;
use Yii;

class ConstructController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'fileapi-upload' => [
                'class' => FileAPIUpload::className(),
                'path' => '@app/web/uploads/'
            ]
        ];
    }

    public function actionIndex()
    {
        $data = Category::find()
            ->all();
        return $this->render('index',[
            'data' => $data,
        ]);
    }

    public function actionProduct($id)
    {
        $data = Products::find()
            ->where(['id_category' => $id])
            ->all();
        return $this->render('product',[
            'data' => $data,
        ]);
    }

    public function actionType($id)
    {
        $type = Type::find()
            ->where(['id_product' => $id])
            ->all();

        if(!empty($type)) {

            return $this->render('type',[
                'data' => $type,
            ]);
        } else {

            $upload = new UploadForm();
            $data ['type'] = $type;
            $data ['upload'] = $upload;

            return $this->render('picture',[
                'data' => $data,
            ]);
        }
    }

    public function actionPicture($id)
    {
        $type = Type::find()
            ->where(['id' => $id])
            ->all();
        $upload = new UploadForm();
        $data ['type'] = $type;
        $data ['upload'] = $upload;

        return $this->render('picture',[
            'data' => $data,
        ]);
    }

}

views/construct/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
?>
<?php Url::remember();?>

<h1>Выберите изделие</h1>
<div class="blocks">
    <?php foreach ($data as $post): ?>
        <div class="object">
            <?= Html::a($post->name, array('construct/product', 'id'=>$post->id)); ?>
        </div>
    <?php endforeach; ?>
</div>

views/construct/picture.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use vova07\fileapi\Widget as FileAPI;

/* @var $this yii\web\View */
?>


<h3><?= Html::a('<', Url::previous()); ?>Выберите источник</h3>
<div class="phone-form">
    <?php $form = ActiveForm::begin(
        [
            'options' => [
                'class' => 'center'
            ]
        ]
    ); ?>

    <div class="upload-button">
        <?= $form->field($data['upload'], 'picture')->widget(
            FileAPI::className(),
            [
                'settings' => [
                    'url' => ['fileapi-upload']
                ],
                'crop' => true,
                'cropResizeWidth' => 400,
            ]
            )->label(false); ?>
    </div>

    <div class="phone-object">
        <?= Html::img(Url::to('@web/uploads/type/') . $data['type'][0]->path_to_picture); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

views/construct/product.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
?>

<h1><?= Html::a('<', Url::previous()); ?><?= Yii::$app->controller->action->id; ?></h1>
<?php Url::remember();?>

<div class="blocks">
    <?php foreach ($data as $post): ?>
        <div class="object">
            <?= Html::a($post->name, array('construct/type', 'id'=>$post->id)); ?>
        </div>
    <?php endforeach; ?>
</div>

views/construct/type.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
?>

<h1><?= Html::a('<', Url::previous()); ?>Выберите макет</h1>
<?php Url::remember();?>

<div class="blocks">
    <?php foreach ($data as $post): ?>
        <div class="object">
            <?= Html::a($post->name, array('construct/picture', 'id'=>$post->id)); ?>
        </div>
    <?php endforeach; ?>
</div>

views/construct/upload.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use vova07\fileapi\Widget as FileAPI;

/* @var $this yii\web\View */
?>

<h1><?= Html::a('<', Url::previous()); ?>Выберите источник</h1>

<?php $form = ActiveForm::begin([
    'options' => ['accept' => 'image/*', 'enctype' => 'multipart/form-data']
]); ?>

<?= $form->field($model, 'file')->fileInput() ?>

<button>Submit</button>

<?php ActiveForm::end(); ?>